M48
; DRILL file KiCad 10.0.0 date 2026-04-02T18:27:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-02T18:27:11-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.900
%
G90
G05
T1
X113.0Y-79.0
T2
X100.3Y-93.0
X113.0Y-93.0
T3
X84.0Y-90.0
X84.0Y-92.54
M30
